### ISSUE TITLE
Accomodate for Linux/Mac discrepancies in `shuf` and `head`

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/english_models_cltk#1]
@free-variation We're off to a good start here!

I made some trivial changes on branch `kj-review`, please update these to master if they look good. Then you can see where I am stuck with `scripts/evaluate_all_models.bash`.

``` python
$ ./scripts/evaluate_all_models.bash
---------- unigram ----------
scripts/split_dataset.bash: line 17: shuf: command not found
head: illegal line count -- 0
Traceback (most recent call last):
  File "src/python/oe_dev.py", line 19, in <module>
    _, acc = make_pos_model(model_type, 'tmp/oe_train.pos', 'tmp/oe_test.pos')
  File "/Users/kyle/english_models_cltk/src/python/train_pos_tagger.py", line 42, in make_pos_model
    return (tagger, tagger.evaluate(test_sents))
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/tag/api.py", line 72, in evaluate
    return accuracy(gold_tokens, test_tokens)
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/metrics/scores.py", line 41, in accuracy
    return sum(x == y for x, y in zip(reference, test)) / len(test)
ZeroDivisionError: division by zero

---------- backoff ----------
scripts/split_dataset.bash: line 17: shuf: command not found
head: illegal line count -- 0
Traceback (most recent call last):
  File "src/python/oe_dev.py", line 19, in <module>
    _, acc = make_pos_model(model_type, 'tmp/oe_train.pos', 'tmp/oe_test.pos')
  File "/Users/kyle/english_models_cltk/src/python/train_pos_tagger.py", line 42, in make_pos_model
    return (tagger, tagger.evaluate(test_sents))
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/tag/api.py", line 72, in evaluate
    return accuracy(gold_tokens, test_tokens)
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/metrics/scores.py", line 41, in accuracy
    return sum(x == y for x, y in zip(reference, test)) / len(test)
ZeroDivisionError: division by zero

---------- crf ----------
scripts/split_dataset.bash: line 17: shuf: command not found
head: illegal line count -- 0
Traceback (most recent call last):
  File "src/python/oe_dev.py", line 19, in <module>
    _, acc = make_pos_model(model_type, 'tmp/oe_train.pos', 'tmp/oe_test.pos')
  File "/Users/kyle/english_models_cltk/src/python/train_pos_tagger.py", line 42, in make_pos_model
    return (tagger, tagger.evaluate(test_sents))
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/tag/api.py", line 72, in evaluate
    return accuracy(gold_tokens, test_tokens)
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/metrics/scores.py", line 41, in accuracy
    return sum(x == y for x, y in zip(reference, test)) / len(test)
ZeroDivisionError: division by zero

---------- perceptron ----------
scripts/split_dataset.bash: line 17: shuf: command not found
head: illegal line count -- 0
Traceback (most recent call last):
  File "src/python/oe_dev.py", line 19, in <module>
    _, acc = make_pos_model(model_type, 'tmp/oe_train.pos', 'tmp/oe_test.pos')
  File "/Users/kyle/english_models_cltk/src/python/train_pos_tagger.py", line 42, in make_pos_model
    return (tagger, tagger.evaluate(test_sents))
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/tag/api.py", line 72, in evaluate
    return accuracy(gold_tokens, test_tokens)
  File "/Users/kyle/venv36/lib/python3.6/site-packages/nltk/metrics/scores.py", line 41, in accuracy
    return sum(x == y for x, y in zip(reference, test)) / len(test)
ZeroDivisionError: division by zero
```

Take a look at what I did on line 17: `shuf $1 > $SHUFFLED_FILE || gshuf $1 > $SHUFFLED_FILE`, so that gshuf gets called for mac users. I assume my `||` trick is working, not totally sure. This `ZeroDivisionError` seems to come out of `head: illegal line count -- 0`. What OS are you now using? I can try on a Linux later, however till then if you can try these on a mac, it'd help speed things along.

**Comment by free-variation** [comment]
OK, I merged your changes -- thank you for the review @kylepjohnson ! -- and fixed the issue causing the ZeroDivisionErrors.  It turns out that `cut` on OSX works a little differently than on e.g. Debian.
